const oldCategories = {
  'vitro': ['Vitro', '#000'],
  'percolators': ['Percolators', '#5e5f95'],
  'glass-bong': ['Glass bong', '#f7ef31'],
  'bazooka': ['Bazooka bong', '#bbdead'],
  'vaporizer_': ['Vaporizer', '#888888'],
  'vaporizer_penvapes': ['Pen vapes', '#888888'],
  'vaporizer_ecigarette': ['E-cigarette', '#888888'],
  'ash-catcher': ['Ash-catcher', '#9cb539'],
  'concentrates': ['Concentrates', '#E0C173'],
  'glass-part': ['Glass part', '#18295a'],
  'acrylique-bong': ['Acrylique bong', '#5dba45'],
  'amber-glass': ['Amber glass', '#f2b03a'],
  'ceramic': ['Ceramic', '#ba2a29'],
  'hookah': ['Hookah', '#46c6f3'],
  'dug-out': ['Dug-out', '#9e761d'],
  'acrylique-pipe': ['Acrylique pipe', '#d6bd42'],
  'metal-pipe': ['Metal pipe', '#4a6aa9'],
  'resin-pipe': ['Resin pipe', '#10ab59'],
  'wood-pipe': ['Wood pipe', '#94201e'],
  'glass-pipe': ['Glass pipe', '#633c99'],
  'spoon': ['Spoon', '#4cc2e8'],
  'bubbler': ['Bubbler', '#d7a3cc'],
  'animal-glass': ['Animal glass', '#639cd6'],
  'polyresine-pipe': ['Polyresin pipe', '#2aab5c'],
  'casing': ['Casing', '#1d6634'],
  'ashtray': ['Ashtray', '#ffdc19'],
  'lighter': ['Lighter', '#02739d'],
  'flags_': ['Flags', '#00B8E6'],
  'flags_music': ['Music', '#00B8E6'],
  'flags_eg': ['ENTMT/GENERIC', '#00B8E6'],
  't-shirt_': ['All Shirts', '#70b722'],
  't-shirt_music': ['T-Shirts Music', '#99FF33'],
  't-shirt_eg': ['T-Shirts ENTMT/GENERIC', '#FF0000'],
  't-shirt_girl-music': ['Girl\'s Shirt Music', '#7519D1'],
  't-shirt_girl-eg': ['Girl\'s Shirt ENTMT/GENERIC', '#FF66FF'],
  'hooded-sweatshirts_': ['Hooded Sweatshirts', '#808080'],
  'hooded-sweatshirts_music': ['Music', '#808080'],
  'hooded-sweatshirts_eg': ['ENTMT/GENERIC', '#808080'],
  'kids-babywear': ['Kids / Babywear', '#19D1A3'],
  'hats-beanies_': ['Hats / Beanies', '#FF0000'],
  'hats-beanies_music': ['Music', '#FF0000'],
  'hats-beanies_eg': ['ENTMT/GENERIC', '#FF0000'],
  'patches_': ['Patches', '#1947D1'],
  'patches_music': ['Music', '#1947D1'],
  'patches_eg': ['ENTMT/GENERIC', '#1947D1'],
  'patches_backpatches': ['Backpatches', '#1947D1'],
  'stickers': ['Stickers', '#FFCC00'],
  'belts_': ['Belts', '#8A2E8A'],
  'belts_music': ['Music', '#8A2E8A'],
  'belts_eg': ['ENTMT/GENERIC', '#8A2E8A'],
  'belt-buckles_': ['Belt Buckles', '#8A2E8A'],
  'belt-buckles_music': ['Music', '#8A2E8A'],
  'belt-buckles_eg': ['ENTMT/GENERIC', '#8A2E8A'],
  'clothing-accessories_': ['Clothing Accessories', '#E84319'],
  'clothing-accessories_music': ['Music', '#E84319'],
  'clothing-accessories_eg': ['ENTMT/GENERIC', '#E84319'],
  'wallets_': ['Wallets', '#FF0000'],
  'wallets_music': ['Music', '#FF0000'],
  'wallets_eg': ['ENTMT/GENERIC', '#FF0000'],
  'bandana': ['Bandana', '#ee3d26'],
  'frame': ['Frame', '#43bc88'],
  'dvd': ['DVD', '#Fcbde7'],
  'book': ['Book', '#9cbde7'],
  'rolling-machine': ['Rolling machine', '#6b2264'],
  'rolling-paper': ['Rolling paper', '#c74c9d'],
  'miscellaneous': ['Miscellaneous', '#888888'],
  'tips': ['Tips', '#93c73d'],
  'grinder': ['Grinder', '#9f7b2c'],
  'stash': ['Stash', '#f67224'],
  'd-tox': ['D-Tox', '#de1958'],
  'knives': ['Knives', '#c5c1c2'],
  'accessories': ['Accessories', '#888888'],
  'adult': ['Adult toyz', '#f4c0d9'],
  'scales': ['Scales', '#adac94'],
  'cleaner': ['Cleaner', '#ee3c26'],
  'legal-alternative': ['Legal alternative', '#633c99'],
  'powder-incence': ['Powder incence', '#222222'],
  'baggies': ['Baggies', '#ee3c26']
};

const store = {
  auth: null,
  categories: Object.keys(oldCategories).map((k, i) => ({
    _id: i,
    link: k,
    name: oldCategories[k][0],
    style: {
      color: oldCategories[k][1]
    }
  }))
};

export default {
  get: key => {
    return key ? store[key] || {} : store;
  },
  set: (key, val) => {
    store[key] = val;
  }
};
